export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOG_OUT = "LOG_OUT";
export const LOAD_ADMIN = "LOAD_ADMIN";

export const SEARCH_USER_KEY_REQUEST = "SEARCH_USER_KEY_REQUEST";
export const SEARCH_USER_KEY_SUCCESS = "SEARCH_USER_KEY_SUCCESS";
export const SEARCH_USER_KEY_FAIL = "SEARCH_USER_KEY_FAIL";

export const ADD_NEW_ITEM_REQUEST = "ADD_NEW_ITEM_REQUEST";
export const ADD_NEW_ITEM_SUCCESS = "ADD_NEW_ITEM_SUCCESS";
export const ADD_NEW_ITEM_FAIL = "ADD_NEW_ITEM_FAIL";
export const ADD_NEW_ITEM_CLEANLOADERROR = "ADD_NEW_ITEM_CLEANLOADERROR";

export const ADD_GLOBAL_TYPES_REQUEST = "ADD_GLOBAL_TYPES_REQUEST";
export const ADD_GLOBAL_TYPES_SUCCESS = "ADD_GLOBAL_TYPES_SUCCESS";
export const ADD_GLOBAL_TYPES_FAIL = "ADD_GLOBAL_TYPES_FAIL";

export const ADD_GLOBAL_PACKAGES_REQUEST = "ADD_GLOBAL_PACKAGES_REQUEST";
export const ADD_GLOBAL_PACKAGES_SUCCESS = "ADD_GLOBAL_PACKAGES_SUCCESS";
export const ADD_GLOBAL_PACKAGES_FAIL = "ADD_GLOBAL_PACKAGES_FAIL";

export const UNVERIFIED_USERS_REQUEST = "UNVERIFIED_USERS_REQUEST";
export const UNVERIFIED_USERS_SUCCESS = "UNVERIFIED_USERS_SUCCESS";
export const UNVERIFIED_USERS_FAIL = "UNVERIFIED_USERS_FAIL";

 